### ISSUE TITLE
TODO for "Complete" Final Product

### ISSUE THREAD

**Issue by erikthedeveloper** [erikthedeveloper/listapp-reactjs-redux-example#5]
Some TODOs and considerations to reach a "complete" status and move on :smile:
### Pre Redux
- [ ] Decide whether or not to scrap current layout/styles in favor of porting to [TodoMvc](http://todomvc.com/)
- [x] Simplify any excessive layout/components.
- [ ] Reduce JS-inline styling. Extract any distractive styles to CSS.
- [x] Rename `TextInput` -> `EditingText`
- [x] Make use of `EditingText` within `ListHeader`
- [x] Further refactor/simplify "draft" concept to work as `<EditingText defaultValue="Start with this value" />` (begin as `EditingText.state` migrate to Redux)
- [x] Tone down the destructuring so as not to be distracting/excessive
- [ ] Revisit [possibly gut/simplify] `apiClient.js` and usages
  - Maybe lightly wrap `request` to simply set baseUrl so that `myRequest('GET', 'lists/')` or `myRequest.get('lists/')`
  - Also ensure no redundant/excessive calls are being made
### Reduxify
- [ ] Promote simpler non-async state to Redux
- [ ] Add "new feature" (filter items [all, complete, active])
- [ ] Promote async "read" operations
- [ ] Promote async "write" operations
- [ ] more...
### More...

...
